CREATE TABLE usuarios (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(100) NOT NULL UNIQUE,
    usuario VARCHAR(30) NOT NULL UNIQUE,
    contrasena VARCHAR(300) NOT NULL,
    estado BOOLEAN NOT NULL
);